### ISSUE TITLE
Generated code fails to build due to wrong scoping on "impl Default for <Enum>"

### ISSUE THREAD

**Issue by joaommartins** [oxidecomputer/typify#136]
When generating code making use of defaults in enums, the scope of the output default implementation is wrong and prevents the generated code to build correctly. 

## Steps to Reproduce

Using the following JSON:
```json
{
    "definitions": {
        "test-enum": {
            "type": "string",
            "enum": ["failure", "skipped", "success"],
            "default": "failure"
        }
    }
}
```

The generated default implementation is the following:
```rust
impl Default for TestEnum {
    fn default() -> Self {
        super::TestEnum::Failure
}
```

## Expected bahaviour
The generated default implementation has the correct scope for the enum generated:
```rust
impl Default for TestEnum {
    fn default() -> Self {
        TestEnum::Failure
}
```
or alternatively:
```rust
impl Default for TestEnum {
    fn default() -> Self {
        Self::Failure
}
```

**Comment by ahl** [comment]
closed by #137
