### ISSUE TITLE
Enums should impl `ToString` or `Display`

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/typify#144]
There's an upstream failure in progenitor where enums in a path that have variants which take a single parameter can't be converted to a sting because they don't implement `Display`.  See the upstream issue https://github.com/oxidecomputer/progenitor/issues/253. To support this usecase we'll need enums to either derive `Display` or implement `ToString`.

**Comment by Kinrany** [comment]
Could this rely on a macro library like `strum`?

**Comment by ahl** [comment]
It could, but in general we try to minimize dependencies. In addition, we try to reduce the reliance on derive macros in particular when we can generate effectively the same code, but more efficiently (i.e. without re-parsing the generated code)

**Comment by Kinrany** [comment]
Behind a feature flag perhaps?

In this case the added impls easily triple the amount of code generated. Having them hidden behind macros makes it easier to inspect the code. Makes it easier to fix code when it runs into [the naming problem](https://github.com/oxidecomputer/typify/issues/384).
