### ISSUE TITLE
Failing to parse spec with "multiple implied types for untyped enum"

### ISSUE THREAD

**Issue by lsh** [oxidecomputer/typify#165]
Hi all, I'm trying to convert the latest [Vega](https://vega.github.io/vega) schema ([v5.22.1 found here](https://vega.github.io/schema/vega/v5.22.1.json)). I was working off the `example-build`, and had a `build.rs` with the following:

```rust
use std::{fs, path::Path};

use schemars::schema::Schema;
use typify::{TypeSpace, TypeSpaceSettings};

fn main() {
    let content = include_str!("v5.22.1.json");
    let schema = serde_json::from_str::<schemars::schema::RootSchema>(content).unwrap();

    let mut type_space = TypeSpace::new(TypeSpaceSettings::default().with_struct_builder(true));
    type_space.add_ref_types(schema.definitions).unwrap();
    let base_type = &schema.schema;
    // Only convert the top-level type if it has a name
    if (|| base_type.metadata.as_ref()?.title.as_ref())().is_some() {
        let _ = type_space.add_type(&Schema::Object(schema.schema)).unwrap();
    }

    let content = format!(
        "{}\n{}",
        "use serde::{Deserialize, Serialize};",
        type_space.to_string()
    );

    let out_file = Path::new("src/gen.rs").to_path_buf();
    fs::write(out_file, &content).unwrap();
}
```

This results in the following error:

`
 thread 'main' panicked at 'multiple implied types for an un-typed enum {Number, Null, String} [Null, String("normal"), String("bold"), String("lighter"), String("bolder"), String("100"), String("200"), String("300"), String("400"), String("500"), String("600"), String("700"), String("800"), String("900"), Number(100), Number(200), Number(300), Number(400), Number(500), Number(600), Number(700), Number(800), Number(900)]'
`

It seems like it has trouble with portions of the schema that use something like `fontWeight`.

Any help (or mentoring to fix the issue) would be appreciated.

**Comment by ahl** [comment]
Thanks for filing this. Do you have an idea for how you'd like the type for titleFontWeight represented in rust?

In general, typify isn't currently great at handling schemas that describe types that have different structure such as a string and a number as in this case.

**Comment by lsh** [comment]
That's a good question. For our needs `"700"` and `700` are the same, but I understand that representing that from a parsing perspective is tough. Ideally we would have something like: 
```rust
pub enum FontWeight {
  Normal,
  Bold,
  Lighter,
  W100,
  /* .. */
  W900,
}
```

**Comment by ahl** [comment]
That's a little tricky to produce programmatically. There's a manual override that may be helpful in this case.

I started pulling out cases where you could then insert a type that you construct by hand:

```rust
    let mut settings = TypeSpaceSettings::default();
    let raw_schema = serde_json::json! {
        {
            "enum": [
              null,
              "normal",
              "bold",
              "lighter",
              "bolder",
              "100",
              "200",
              "300",
              "400",
              "500",
              "600",
              "700",
              "800",
              "900",
              100,
              200,
              300,
              400,
              500,
              600,
              700,
              800,
              900
            ]
          }
    };
    let schema = serde_json::from_value(raw_schema).unwrap();
    settings.with_conversion(schema, "MyEnum", ["FromStr"].into_iter());
    let raw_schema = serde_json::json! {
        {
            "enum": [
                null,
                "start",
                "middle",
                "end"
            ]
        }
    };
    let schema = serde_json::from_value(raw_schema).unwrap();
    settings.with_conversion(schema, "AnotherEnum", ["FromStr"].into_iter());
    let raw_schema = serde_json::json! {
        {
            "not": {
            "enum": [
                "checkbox",
                "radio",
                "range",
                "select"
            ]
            }
        }
    };
    let schema = serde_json::from_value(raw_schema).unwrap();
    settings.with_conversion(schema, "Yolo", ["FromStr"].into_iter());

    let mut type_space = TypeSpace::new(&settings);
```

I didn't keep pulling that thread, but you can keep manually overriding schemas that typify doesn't know how to handle. I did find a clear area to improve typify to handle this schema albeit narrowly: #166

**Comment by ahl** [comment]
#168 is going to "handle" all cases except that `FontWeight` case above. I say "handle" in that it won't crash, but the output may not be what you'd like. Feedback on the generation is welcome.

**Comment by lsh** [comment]
Hi, thank you for these updates, and for looking into this!

I might still be misunderstanding a little bit about how to use the generator. I tried using your above example of hand constructed types and appending a `println!("{}", type_space.to_string())`, but it seems to only return `\n`. What kind of output should I be expecting for `TypeSpace` with the above? Thank you again :)

**Comment by ahl** [comment]
I added it to the test suite:
https://github.com/oxidecomputer/typify/blob/main/typify-impl/tests/test_github.rs#L31
The output:
https://github.com/oxidecomputer/typify/blob/main/typify-impl/tests/vega.out

**Comment by lsh** [comment]
This is great, thank you! I would say the scope of this issue is definitely fulfilled, and I'm looking forward to trying out the generated types

**Comment by ahl** [comment]
I'd love your feedback on the generated types. Some of them are pretty gnarly:

```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(untagged)]
pub enum AlignValueVariant0ItemSubtype1Subtype1Subtype0 {
    Variant0(SignalRef),
    Variant1 {
        value: AlignValueVariant0ItemSubtype1Subtype1Subtype0Variant1Value,
    },
    Variant2 {
        field: Field,
    },
    Variant3 {
        range: AlignValueVariant0ItemSubtype1Subtype1Subtype0Variant3Range,
    },
}
```
