### ISSUE TITLE
Panick for float with minimum/maximum/multiple_of/etc

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/typify#169]
Sample schema which triggers this panick:
```json
    "idNum": {
      "type": "integer",
      "maximum": 30,
      "minimum": 20,
      "multipleOf": 5
    }
```
Result:
> thread 'main' panicked at 'assertion failed: validation.minimum.is_none()', [/home/jayvdb/.cargo/git/checkouts/typify-288d5a84bbbe6a46/aa5e5a6/typify-impl/src/convert.rs:720:13](https://github.com/oxidecomputer/typify/blob/aa5e5a6c413920385af6b2c74252ea7d55d3d138/typify-impl/src/convert.rs#L709-L722)

https://github.com/oxidecomputer/typify/pull/109 by @justinmmott provided a fix for that, but has been closed unmerged.
Keen to hear what are the next steps to resolving this. I can help get this solved, I will be able to use unpatched typify, which makes it much easier to be maintaining a few enhancements for progenitor such as https://github.com/oxidecomputer/progenitor/pull/252

**Comment by ahl** [comment]
What types or code would you ideally like to see generated for constructs such as this?

**Comment by jayvdb** [comment]
Ideally a type which provides constraints on its value according to the minimum/maximum/multiple_of.

Obviously because I am using https://github.com/oxidecomputer/typify/pull/109 , I am happy with its output.

But I am not looking for ideal.  I would be happy with "does not panick".  Perhaps a generation flag could be added to "allow generation ignoring unsupported features", default disabled of course, which would skip these assertions and others like it, so that the generated code will gracefully degrade, to normal unconstrained integers in this case, and "buyer beware" obviously applies.

If https://github.com/oxidecomputer/typify/pull/109 bit rots too much, my other option is to post process the OpenAPI from the vendors product to remove the unsupported features so typify doesnt panick.

**Comment by ahl** [comment]
This schema no longer seems to be crashing for me. Can you please give it a try with the code in `main` and let me know what you find?

```json
{
  "title": "TestType",
  "type": "object",
  "properties": {
    "number": {
      "type": "integer",
      "maximum": 30,
      "minimum": 20,
      "multipleOf": 5
    }
  }
}
```

is giving me

```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TestType {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub number: Option<i8>,
}
```

... it's not the best, but it's not crashing..

**Comment by jayvdb** [comment]
The issue title has been updated as this issue is primarily about the asserts at https://github.com/oxidecomputer/typify/blob/d1cae0f/typify-impl/src/convert.rs#L868-L872 in `convert_number`, which are hit when there is a non-integer with validation.
i.e. [`convert_integer`](https://github.com/oxidecomputer/typify/blob/d1cae0f/typify-impl/src/convert.rs#L727) doesnt have these asserts; there is nothing equivalent for floats.

e.g. this crashes typify `main` (d1cae0f).

```yaml
    Arc:
      type: object
      properties:
        ...
        radius:
          type: number
          description: Must be >0
          example: 1.0
          minimum: 0.0
```
