### ISSUE TITLE
update changelog and cut a 0.0.11 release

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/typify#173]
lots has changed...

**Comment by jayvdb** [comment]
Do we have a list of any release blockers?  I can throw some hours into anything that needs investigating/fixing.

Now that I am pre-processing my yaml and post-processing the rust, most of my use cases are solved, and it would be lovely to be using a released typify/progenitor-impl for those cases.  A few of my inputs trigger https://github.com/oxidecomputer/typify/issues/169 , but it looks like that is in the too hard basket so shouldnt block a release.

**Comment by ahl** [comment]
I was hoping to get #204 in, and to take a pass through the docs.

**Comment by coreyja** [comment]
👋 I'll try and make another pass at #204 this evening (definitely this weekend)!

**Comment by ahl** [comment]
https://crates.io/crates/typify/0.0.11
