### ISSUE TITLE
Potentially misplaced `deny_unknown_fields` when schema has optional fields

### ISSUE THREAD

**Issue by svet-b** [oxidecomputer/typify#244]
I have a simple JSON schema:
```json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "title": "Example schema",
    "type": "object",
    "required": [
        "readings"
    ],
    "properties": {
        "readings": {
            "type": "object",
            "title": "Readings to take",
            "additionalProperties": {
                "type": "object",
                "title": "Reading schema"
            },
            "minProperties": 1
        }
    }
}
```
I.e. an `object` with a `readings` key, which is itself an object with one or more objects nested under it.

I ran `cargo typify --no-builder` on it (v0.0.11) and it yielded the following Rust definitions:
```rust
#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ExampleSchema {
    pub readings: ReadingsToTake,
}
impl From<&ExampleSchema> for ExampleSchema {
    fn from(value: &ExampleSchema) -> Self {
        value.clone()
    }
}
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ReadingsToTake {
    #[serde(flatten)]
    pub extra:
        std::collections::HashMap<String, std::collections::HashMap<String, serde_json::Value>>,
}
impl From<&ReadingsToTake> for ReadingsToTake {
    fn from(value: &ReadingsToTake) -> Self {
        value.clone()
    }
}
```
The `#[serde(deny_unknown_fields)]` line appears potentially misplaced, and prevents the parsing of valid JSON.

Let's say I have the JSON string
```json
{
    "readings": {
        "something": {"a": 1}
    }
}
```
Trying to load this into the Rust structure results in an `Error("unknown field `something`")` - because the field is indeed not explicitly defined in the structure, and not allowed by the `deny_unknown_fields`.

I played around a bit, and it seems that if I remove _either_ the `additionalProperties` or `minProperties` directives from the schema, the `deny_unknown_fields` line goes away.

It's quite possible that I'm doing something wrong, but at first pass this feels like a bug.

**Comment by svet-b** [comment]
Just to add a couple of observations:
- If the `additionalProperties` key is removed from the JSON schema (but `minProperties` is left in), then the Rust definition looks right (and doesn't contain the `deny_unknown_fields` line). But it of course it no longer specifies the schema of what's under `ReadingsToTake`, which isn't what I want.
- If the `minProperties` key is removed from the JSON schema (but `additionalProperties` is left in), the `ReadingsToTake` struct isn't defined at all. I'm not sure what to make of that.

**Comment by ahl** [comment]
It turns out `deny_unknown_fields` is incompatible with `flatten`: https://serde.rs/container-attrs.html#deny_unknown_fields

This is disappointing, but perhaps unsurprising. `typify` had been relying on a false understanding of how those attributes interacted.
