### ISSUE TITLE
`clone-on-copy` Clippy warning in generated code

### ISSUE THREAD

**Issue by mbrobbel** [oxidecomputer/typify#245]
The following impl results in the a Clippy (`clone-on-copy`) warning for simple enums that derive `Copy`:

https://github.com/oxidecomputer/typify/blob/6d77f63b3dc5312cd36549507f941cb5d783600e/typify-impl/src/type_entry.rs#L903-L907

```console
error: using `clone` on type `Decomposable` which implements the `Copy` trait
   --> /home/runner/work/substrait-rs/substrait-rs/target/debug/build/substrait-7d34e5b12ba1084d/out/substrait_text.rs:143:9
    |
143 |         value.clone()
    |         ^^^^^^^^^^^^^ help: try dereferencing it: `*value`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
    = note: `-D clippy::clone-on-copy` implied by `-D warnings`
```

[Log](https://github.com/substrait-io/substrait-rs/actions/runs/4563172157/jobs/8051336810?pr=84#step:5:286)

**Comment by ahl** [comment]
I would suggest ignoring that warning. We don't check if types `impl Copy` before calling `clone()` and I'm not sure it's worth doing.
