### ISSUE TITLE
Allow replacing `chrono` types

### ISSUE THREAD

**Issue by drahnr** [oxidecomputer/typify#251]
Currently the generated types for `date-format` and `date` are using `chrono` based types, partially marked as deprecated. It'd be great if the types could be replaced with custom types.

**Comment by ahl** [comment]
Check out "Conversion overrides" in the docs: https://docs.rs/typify/0.0.11/typify/#conversion-overrides

Does that work for you if you swap "uuid" for "date" or "date-time"?

**Comment by drahnr** [comment]
I seem to have missed that section, I am just a second degree user of `typify` through `progenitor`, where it's not exposed. Closing.

**Comment by ahl** [comment]
Did the mechanism in progenitor work for you? I'd love to improve the docs and realize this feature (and others) are a bit obscure. If you have suggestions (or a PR!) they would be helpful and welcome.

**Comment by drahnr** [comment]
It did! I'll have a few small PRs ready soon™.
