### ISSUE TITLE
deny_unknown_fields on a oneOf enum prevents use of flattened additionalProperties

### ISSUE THREAD

**Issue by BadMagic100** [oxidecomputer/typify#280]
When a subschema uses a oneOf where one variant uses additionalProperties, all objects fail to deserialize claiming that there is no matching variant for the generated untagged enum. Upon inspection, it seems like during a successful generation, the deny_additional_fields attribute is added to the object, which is [documented to not play nicely with the flatten attribute](https://serde.rs/container-attrs.html#deny_unknown_fields). Note that this behavior is not consistently seen on all such enums, so it might be an edge case with my example specifically. Adding an explicit `"additionalProperties": true` on the object causes generation to fail.

Sample schema fragment:
```json
"References": {
    "oneOf": [
        { 
            "$comment": "An array of mod names. Version is inferred to be @modlinks." ,
            "type": "array", 
            "items": { "type": "string" }
        },
        { 
            "$comment": "Mapping of mod name to the desired version",
            "type": "object", 
            "additionalProperties": 
            { 
                "oneOf": [
                    { "$ref": "#/definitions/StringVersion" },
                    { "$ref": "#/definitions/ReferenceDef" }
                ]
            }
        }
    ]
}
```

The corresponding generated Rust code is:
```rs
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(untagged, deny_unknown_fields)] //problem is here, because Variant1.extra is flattened
pub enum References {
    Variant0(Vec<String>),
    Variant1 {
        #[serde(flatten)]
        extra: std::collections::HashMap<String, ReferencesVariant1ExtraValue>,
    },
}
```

**Comment by BadMagic100** [comment]
Obviously I think the easy fix is to just not emit the `deny_unknown_fields` on the enum, but I'm not sure if that's generally safe (it's certainly safe in my case since one option is an array and the other is an object, can't have both) or what specifically causes it to be emitted in this case.

**Comment by ahl** [comment]
I think this is similar to #244. This is, however, particularly lousy codegen. I think I'd rather see:

```rust
pub enum References {
    Variant0(Vec<String>),
    Variant1(std::collections::HashMap<String, ReferencesVariant1Value>)
```

Regardless that at a minimum we should never issue `deny_unknown_fields` and `flatten` together.
