### ISSUE TITLE
Cannot generate schema from reference hyperschema

### ISSUE THREAD

**Issue by jasminemoore-verses** [oxidecomputer/typify#290]
Running cargo-typify 0.0.12.

Input at: https://gist.github.com/jasminemoore-verses/efc6db1f73d23adbb3a8d94a0bcd4cf2 (input.json)
Errors at: https://gist.github.com/jasminemoore-verses/efc6db1f73d23adbb3a8d94a0bcd4cf2 (output.txt)

The input document is a modified version of "draft-07-schema.json", the JSON Schema Metaschema from 2017. Self-references cannot be handled (see https://github.com/oxidecomputer/typify/issues/289). The problems here are less clear.

**Comment by ahl** [comment]
The initial error is that we don't currently handle the general case of `type` arrays:

```json
  "type": ["object", "boolean"],
```

I see other looming problems such as `"if": {"$ref": "#"},` i.e. a ref to nothing? and `"$ref": "#/definitions/schemaArray"` which doesn't appear to be defined in this schema.

**Comment by jasminemoore-verses** [comment]
According to https://json-schema.org/understanding-json-schema/structuring.html#recursion , "#" as a "$ref" target should refer to the schema currently being parsed. ("#/definitions/schemaArray" was removed as it refers to "#", which could not be resolved (see #289 ), but is absolutely an error in this schema as presented.)

**Comment by ahl** [comment]
See the resolution of #289
