### ISSUE TITLE
Invalid schema panic when using `required` with `oneOf`

### ISSUE THREAD

**Issue by spencerwilson** [oxidecomputer/typify#312]
note: I'm not 100% sure if this is distinct from https://github.com/oxidecomputer/typify/issues/272

cargo-typify 0.0.13 panics with "not yet implemented: invalid (or unexpected) schema" given the following input:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Table Schema",
  "type": "object",
  "required": [
    "fields",
    "reference"
  ],
  "oneOf": [
    {
      "properties": {
        "fields": {
          "type": "string"
        },
        "reference": {
          "type": "string"
        }
      }
    },
    {
      "properties": {
        "fields": {
          "type": "number"
        },
        "reference": {
          "type": "string"
        }
      }
    }
  ]
}
```

- This is an [SSCCE](http://sscce.org/) derived from the schema provided on this page: https://specs.frictionlessdata.io/table-schema/ I may have oversimplified it and now it admittedly looks contrived.
- The bit I've excerpted may have been generated from this YAML segment: https://github.com/frictionlessdata/specs/blob/9e4d58012d80190574d0a1d7038abe4924f9e714/schemas/dictionary/tableschema.yml#L147-L194
- The use case is described in prose here: https://specs.frictionlessdata.io/table-schema/#foreign-keys tl;dr two properties on an object are coupled together: either both are strings, or both are arrays-of-strings (of equal length, though this constraint is not expressed in the schema). In this case the properties' values represent tuples of columns in two tables.

I've noticed that if I delete the `required` constraint, or if I make it an empty array, the panic does not occur.

**Comment by ahl** [comment]
This seems to have been addressed now:

```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(untagged)]
pub enum TableSchema {
    Variant0 { fields: String, reference: String },
    Variant1 { fields: f64, reference: String },
}
impl From<&TableSchema> for TableSchema {
    fn from(value: &TableSchema) -> Self {
        value.clone()
    }
}
```

That looks pretty good to me; I could imagine (maybe) something like this being better:

```rust
pub struct TableSchema {
    fields: StringOrNumber,
    reference: String,
}

#[serde(untagged)
pub enum StringOrNumnber {
    String(String),
    Number(f64),
}
```

I've been thinking about making transformations like that, but it's probably down the road quite a ways. Let me know if you're happy with the current output, and what you think of the maybe better output.
