### ISSUE TITLE
Arrays wrongly require `items`

### ISSUE THREAD

**Issue by spencerwilson** [oxidecomputer/typify#314]
Given
```json
{
  "title": "hello",
  "type": "array",
  "minItems": 1,
  "uniqueItems": true
}
```
cargo-typify 0.0.13 errors:
```
% cargo typify other.json
Error:
   0: Failed to convert JSON Schema to Rust code
   1: Schema conversion failed
   2: schema invalid: unhandled array validation ArrayValidation {
          items: None,
          additional_items: None,
          max_items: None,
          min_items: Some(
              1,
          ),
          unique_items: Some(
              true,
          ),
          contains: None,
      }
...
```

In the latest JSON Schema spec ([2020-12 Core](https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.3.1.2-4)),
> Omitting [`items`] has the same assertion behavior as an empty schema.

typify _does_ do something reasonable when adding an `"items": {}` to the schema: it generates a struct like
```rust
pub struct Hello(pub Vec<serde_json::Value>);
```

(arguably the minimum reasonable data structure would be something like a `Vec<serde_json::Value>`, but not sure if typify should try to be that clever)

**Comment by ahl** [comment]
Thanks for the bug report; this is a pretty straightforward fix (and similar to fixes applied recently to other schema archetypes).

Basically, change
```rust
    fn convert_array<'a>(
        &mut self,
        type_name: Name,
        metadata: &'a Option<Box<Metadata>>,
        validation: &ArrayValidation,
    ) -> Result<(TypeEntry, &'a Option<Box<Metadata>>)> {
```
... to take an `Option<ArrayValidation>` instead...

PRs welcome if I don't get to it in the over the next couple of weekends.
