### ISSUE TITLE
Compile time safe builder required fields

### ISSUE THREAD

**Issue by kellpossible** [oxidecomputer/typify#335]
At the moment the builder can crash when the required fields are not specified.
I would like to propose an alternative method  version of the `Type::builder()` function which accepts the required fields, either as arguments `Type::builder(field1, field2)` or as a new struct, perhaps called `RequiredType` (`Type::builder(RequiredType { field1, field2 })`).

**Comment by kellpossible** [comment]
The second proposal does not require positional arguments, struct fields can be in any order you like :slightly_smiling_face:  `Type::builder(RequiredType { field1, field2 })` or `Type::builder(RequiredType { field2, field1 })`.

I'm already using the type without the builder, but it required specifying all the optional fields, which may get annoying if new optional fields are introduced. Usually I would get around this by using:

```rust
Type {
    field,
    ..Type::default()
}
```

However having a default implementation on a struct which has required fields also seems a little dangerous, now it's possible to construct the struct without specifying the required fields. One of the benefits of the builder pattern in this situation is that you can have the best of both worlds.

```rust
Type::builder(RequiredType { field1, field2 })
    .field3(field3);
// field4 is optional and may be omitted.
// Any future optional fields may also be omitted.
 ```

**Comment by ahl** [comment]
I skimmed over that in your initial proposal. It's a neat idea. How would you suggest we name that `RequiredType`?

Currently arguments to the builder methods must `impl TryInto<TypeOfTheField>` which has been handy for a bunch of uses... but does conflict with your idea of having infallible builders.

Also bear in mind that you can optionally apply whatever derive macros you like to generated types. So if you have your own builder you want to use, you could just use it--it doesn't necessarily need to be a part of `typify`'s generation.

**Comment by kellpossible** [comment]
> How would you suggest we name that RequiredType

Good question! Naming is always the hardest, perhaps it could live in its own module like the builders? `required::Type`?

> Also bear in mind that you can optionally apply whatever derive macros you like to generated types. So if you have your own builder you want to use, you could just use it--it doesn't necessarily need to be a part of typify's generation.

True true

**Comment by kellpossible** [comment]
Actually I'm not sure it's possible with a derive to distinguish between optional fields, and fields with the type:

```json
"oneOf": [
    {
        "type": "string"
    },
    {
        "type": "null"
    }
]
```

?

**Comment by kellpossible** [comment]
An alternative suggestion received from a colleague was to split the struct into two, one struct containing the required fields (without `Default` implementation) and one struct containing the optional fields (with `Default` implementation). These two halves would be combined to form the completed struct. This would require less code to be generated than a builder pattern and would be just as easy to use I think?

For example one possible way to do this (there are many):

```rust
struct Type {
    required_field: String,
    optional_field1: Option<String>,
    optional_field2: Option<String>,
}

struct RequiredType {
    required_field: String
}

#[derive(Default)]
struct OptionalType {
    optional_field1: Option<String>,
    optional_field2: Option<String>,
}

impl Type {
    pub fn build(required: RequiredType, optional: OptionalType) -> Self {
        Self {
            required_field: required.required_field,
            optional_field1: optional.optional_field1,
            optional_field2: optional.optional_field2,
        }
    }
}


Type::build(
    RequiredType {
        required_field: "Required".to_owned(),
    },
    OptionalType {
        optional_field2: "Optional 2".to_owned(),
        ..OptionalType::default()
    }
}
```

**Comment by ahl** [comment]
My apologies for the delayed response here. I like this idea, however I think it makes more sense as a derive macro applied to generated types. BUT it could be implemented in typify 1. in a way that would be easily enabled / disabled (e.g. like the `struct_builder` option) and 2. relatively off to the side i.e. not interwoven with lots of other stuff, I would seriously consider a PR. I do think that independent of typify it would make for a very useful derive macro.

I'm planning on closing this issue, but--again--would welcome a PR with the properties above.
