### ISSUE TITLE
cannot convert type string with format i64

### ISSUE THREAD

**Issue by tzilist** [oxidecomputer/typify#39]
When we have a property with some field like so:

```
        "properties": {
          "iterations": {
            "format": "int64",
            "type": "string"
          },
```

Typify crashes with a panic

```
Caused by:
  process didn't exit successfully: `/Users/<redacted>/projects/<redacted>/crates/target/debug/build/<redacted>-631c4662e317d757/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'not yet implemented: Some(
      "int64",
  )', /Users/<redacted>/.cargo/git/checkouts/typify-288d5a84bbbe6a46/b712fe6/typify-impl/src/convert.rs:418:26
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ahl** [comment]
Interesting. What do you expect to happen with the combination of `type` = `string` and `format` = `int64`?

**Comment by tzilist** [comment]
Hmm good question. I suppose it should give back an i64? Maybe it would be good to have string types just fall back to a regular old string if it doesn't know what type of format it is?

**Comment by tzilist** [comment]
That makes sense! I was converting a google discovery formatted api (big query) to open api, so that might be a bug in the tool there. That being said it kind of made sense, since all of the fields are an elapsed time in ms. Thanks for taking a look at this!
