### ISSUE TITLE
Recursive references block the struct generation

### ISSUE THREAD

**Issue by taorepoara** [oxidecomputer/typify#404]
I tried to convert a schema that have recursive references and typify do it well but the Rust compiler fails with the next error message: `recursive without indirection`

It seems that Rust does not manage recursive typing without inderection like `Box` or Rust reference `&`.

Here is a simple example of recursive references that fails:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "A",
  "type": "object",
  "properties": {
    "a": {
      "type": "string"
    },
    "b": {
      "$ref": "#/definitions/B"
    }
  },
  "definitions": {
    "B": {
      "title": "B",
      "type": "object",
      "properties": {
        "a": {
          "$ref": "#"
        },
        "b": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by taorepoara** [comment]
Actually this has been resolved but not released yet.

**Comment by ahl** [comment]
Released! https://crates.io/crates/cargo-typify/0.0.14
