### ISSUE TITLE
Assertion failure in convert_all_of

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/typify#443]
The following openapi fails in progenitor 0.4.0 (typify 0.0.14) and `main`

```yaml
---
openapi: 3.0.3
info:
  title: progenitor-0.4.0-breakage
  version: 0.4.0
paths: {}
components:
  schemas:
    Action:
      type: string
      enum:
        - foo
    Notification:
      allOf:
        - $ref: "#/components/schemas/Action"
        - type: object
          properties:
            action:
              $ref: "#/components/schemas/NotificationAction"
    NotificationAction:
      type: string
      enum:
        - bar
```
The error is in typify
```
typify-impl/src/convert.rs:1140:9:
  assertion `left != right` failed
    left: Bool(false)
   right: Bool(false)
```

In `convert_all_of`, this is failing when `type_name` is `Required("Notification")`

**Comment by ahl** [comment]
So 100% a panic is bad--agreed. But what do we want the output to look like here? The type `Notification` would need to be both a string and an object. I think the only result would be something like the `Never` type we added recently.
