### ISSUE TITLE
use custom error type instead of Strinng/&str in generated code

### ISSUE THREAD

**Issue by sify21** [oxidecomputer/typify#459]
currently, the error type in generated code is `String` or `&'static str`.

`String` is used in `impl TryFrom<BuilderType> for super::Type`

`&'static str` is used in `impl TryFrom<String> for Type` and `impl FromStr for type`

it's better to define a custom error type to conform to `thiserror` or `anyhow`.

**Comment by ahl** [comment]
It's a valid point that using two different types for errors might be confusing. I'm not convinced that a custom error type would provide value--what would you imagine consumers doing with the error type other than extracting a string from it? And I definitely don't want to add the requirement that consumers depend on `thiserror` or `anyhow`.

**Comment by sify21** [comment]
It's quite possible that users have already used `thiserror/anyhow` for error-handling. In my case I want to report this error up in the call stack, currently I have to append `.map_err(|e:String|anyhow!(e))` everywhere, which is quite tedious. 

It can be done by defining a type that implements the trait `std::error:Error`, `anyhow::Result` can recognize those error types.

**Comment by ahl** [comment]
Your point about the use of the error is well taken. How about for now:

```rust
mod error {
    struct Error(pub String);
    impl std::error::Error for Error { .. }
}
```

**Comment by sify21** [comment]
Yeah exactly what I'm thinking, a simple wrapper around string would be enough for my current use case
