### ISSUE TITLE
Potential misgeneration: `Vec<T>` instead of `Option<Vec<T>>`

### ISSUE THREAD

**Issue by woodruffw** [oxidecomputer/typify#464]
First of all, thanks for `typify`! I'm evaluating it for some code generation tasks, and it's very pleasant to use.

I'm currently running into what I *think* is a misgeneration. I have an object schema with a property like this:

```json
        "features": {
          "description": "Long description omitted",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Feature"
          }
        },
```

where `features` is **not** in the `required` set.

## Expected behavior

Since `features` is specified as a property but is not listed as `required`, I expect it to have a generated type of `Option<Vec<Feature>>`.

## Actual behavior

When generated (currently using the `import_types!` macro), I get `Vec<Feature>` rather than `Option<Vec<Feature>>`.

## Additional context

This only seems to happen with "compound" types, not primitive ones. I have another optional field in my definition:

```json
        "max_chain_depth": {
          "title": "Max Chain Depth",
          "description": "The maximum chain-building depth",
          "type": "integer"
        }
```

...and this gets generated as `Option<i64>`, as expected.

I haven't minimized this yet, but you can see my in-progress debugging on https://github.com/trailofbits/x509-limbo/pull/128. Running `cargo doc` on that branch should produce the mis-generated types.

## Alternatives considered

I have control over the schema in this case, so I can (and likely will) tweak it to simply avoid `Option<Vec<T>>` types. But I think this still needs a more general fix!

**Comment by ahl** [comment]
This is an interesting case that has come up before and I'm not entirely sure how to address it. You can use the `cargo-typify` tool to see the code that's generated and if you do, you get something like this:

```rust
    #[doc = "Long description omitted"]
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub features: Vec<Feature>,
```

That is to say: the `serde` annotations tell part of the story that might not be evident. The default is an empty `Vec` and it's omitted from serialization if it's empty.

Also if I use the `builder` function on the type that contains the member `features` it will fill in that default value e.g.

```rust
TestCase::builder().id("abc::def").description("foo")...try_into().unwrap();
```

I think an important question is if both `"features": []` and the `features` property being absent are important and distinct states to model. Your feedback would be welcome here. #319 is a similar issue to consider.

**Comment by woodruffw** [comment]
Thanks for the fast and detailed response!

Yeah, this is an interesting case -- `skip_serializing_if = "Vec::is_empty"` makes sense to me in the serialization case. My problem really only manifests in the deserialization case, since `#[serde(default)]` only applies when the field is missing, not explicitly marked as `null`.

Thinking about that more, I _think_ my original schema generation was just plain incorrect -- `features` should be an `anyOf` with `array` and `null` as child types; without that `anyOf`, `typify` is correct to generate this as `Vec<Feature>`.

Given that, I think this is safe to close as user error/PEBKAC -- `typify` is doing something reasonable in this case, and the schema itself is just wrong 🙂

**Comment by woodruffw** [comment]
To round things out: the context here was that Pydantic V1 generated the original `features` schema; with Pydantic V2 I get this instead:

```json
        "features": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/$defs/Feature"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "omitted",
          "title": "Features"
        },
```

...which has the `anyOf` as expected.

**Comment by ahl** [comment]
I **think** another way to express this would be:

```json
        "features": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/Feature"
          },
          "description": "omitted",
          "title": "Features"
        }
```

Both seem to generate the same rust code.

> typify is doing something reasonable in this case...

Reasonable, but there are other options; unclear of what the best generation is or if there are always instances where one my prefer to have/omit the `Option` wrapper...

**Comment by ahl** [comment]
While/if I still have you; it looks like you migrated from `schemafy`--was that not addressing your needs?

**Comment by woodruffw** [comment]
> While/if I still have you; it looks like you migrated from `schemafy`--was that not addressing your needs?

Unfortunately not -- `schemafy` only supported Draft 4 while Pydantic (and other components I'm using) have moved onto Draft 7 (and newer), and it looks like development on it is currently stalled: https://github.com/Marwes/schemafy/issues/77
