### ISSUE TITLE
Arrays with fixed list of item types

### ISSUE THREAD

**Issue by zeiste1** [oxidecomputer/typify#477]
I have several structures like this in my json schema and would expect this to typify into a Rust Tuple:

`{
  "title": "TestSchema",
  "type": "array",
  "items": [
    {
      "type": "string"
    },
    {
      "type": "integer"
    },
    {
      "type": "boolean"
    }
  ]
}`

When I run `cargo typify test_schema.json` this produces the Error `invalid schema for <unknown type>: unhandled array validation ArrayValidation`. Am I missing something or are structures like this not yet supported?

**Comment by ahl** [comment]
Try adding in `"minItems": 3, "maxItems": 3`. Without that, we'd need a more complex type:

```rust
pub enum TestSchema {
   N0,
    N1(String),
    N2(String, i64),
    N3(String, i64, bool),
    NN(String, i64, bool, Vec<serde_json::Value>),
}
```

In other words, all these values would validate against that schema:
```
[]
["one", 1, true, "potato", { "foo": "bar" }]
["howdy"]
```

**Comment by ahl** [comment]
Checking in on this: my inclination is to close this. We can re-open if what I described above doesn't work for you or if we're missing something. Thanks.
