### ISSUE TITLE
Merge oneOf with many compatible enums of a single value

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/typify#497]
https://github.com/OAI/OpenAPI-Specification/issues/348#issuecomment-1484163189 is apparently the best way to describe enum values, like

```json
    "enum-value-descriptions": {
      "type": "object",
      "description": "https://github.com/OAI/OpenAPI-Specification/issues/348#issuecomment-1484163189",
      "oneOf": [
        {
          "enum": ["A"],
          "description": "An A"
        },
        {
          "enum": ["B"],
          "description": "A B"
        }
      ]
    }
```

Typify generates a bunch of variants for the above, when they could be collapsed into a single Rust enum.

**Comment by ahl** [comment]
Thanks for filing this. Today we get something like this:

```rust
pub enum Thing {
    Variant0(ThingVariant0),
    Variant1(ThingVariant1),
}

pub enum ThingVariant0 {
    A,
}

pub enum ThingVariant1 {
    B,
}
```

Awful! The good news is that a bunch of recent refactoring has been oriented around addressing precisely this kind of weirdness. In particular, my plan is to do a "simplification" or "canonicalization" pass in the `oneOf` handling before trying to map it against various encodings of enums.

As another example:

https://github.com/oxidecomputer/typify/blob/1f97f167923f001818d461b1286f8a5242abf8b1/typify/tests/schemas/merged-schemas.rs#L904-L919

There's no reason this shouldn't be an externally tagged variant:

```rust
pub enum WeirdEnum {
   #[serde(rename = "pattern")]
    Pattern(String),
   #[serde(rename = "patterns")]
    Patterns(String),
   #[serde(rename = "pattern-either")]
    PatternEither(String),
    #[serde(rename = "pattern-regex")]
    PatternRegex(String),
}
```

**Comment by ahl** [comment]
On closer inspection, there are two slightly different issues. The first is that the type of your schema is `object`. Arguably, typify should be rejecting this because there is no value that satisfies the schema (i.e. is an object **and** is either "A" or "B").

A more obvious error from typify is that it requires the subschemas to have `"type": "string"`. This should be unnecessary, and I've got a PR to fix it (see #500).

**Comment by jayvdb** [comment]
Sorry the 'object' bit was my mistake.

https://github.com/OAI/OpenAPI-Specification/issues/348#issuecomment-1484163189 says to use `type: string`

**Comment by ahl** [comment]
> Sorry the 'object' bit was my mistake.

I was just observing that this is another gap in typify's logic--it should either register some sort of error saying that this type is unsatisfiable or produce some sort of `Never` type (e.g. `enum Never{}`).
