### ISSUE TITLE
sanitize keys to raw identifiers instead of postfixing with `_`

### ISSUE THREAD

**Issue by nyarthan** [oxidecomputer/typify#541]
With a schema like this, that has a property key `type`:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/obj",
  "definitions": {
    "obj": {
      "type": "object",
      "properties": {
        "type": { "type": "string" }
      },
      "required": ["type"],
      "additionalProperties": false
    }
  }
}
```
The resulting struct would be:
```rust
pub struct Obj {
    #[serde(rename = "type")]
    pub type_: String,
}
```

I think a better way would be to use [Raw identifiers](https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html) instead of a postfix to ensure the key is not a rust ident.

This is a more idiomatic approach to use keywords as properties and also allows getting rid of the `serde(rename = "...")` attribute since serde handles Raw identifiers out of the box.
```rust
pub struct Obj {
    pub r#type: String,
}
```

**Comment by nyarthan** [comment]
While playing around with this, I came to the realization that this will not work for the keys `super`, `self`, `Self`, `extern` and `crate` (https://internals.rust-lang.org/t/raw-identifiers-dont-work-for-all-identifiers/9094/2). So this approach might not be desirable as it would be inconsistent for these specific keys.

**Comment by ahl** [comment]
Yeah I've thought about using that after I discovered that syntax... but as you say it's not without its own complexity.

**Comment by ahl** [comment]
I'm going to close this. I'm amenable to reconsidering if you think the inconsistency is worth it. Suffice to say: I don't love any of the options.
