### ISSUE TITLE
Difference with progenitor?

### ISSUE THREAD

**Issue by louis030195** [oxidecomputer/typify#562]
Hi! Great work!

I'm looking for a lib that parse an `openapi.yaml` into types (don't care about client, just types). Most things I found on internet for rust seems dead/unmaintained/awful.

I'm trying to understand what's the diff with
https://github.com/oxidecomputer/progenitor

?

I'm going to give a shot to typify first

**Comment by ahl** [comment]
Progenitor uses typify to generate types. If you have an OpenAPI document, I'd suggest you start with progenitor and ignore the generated client. See also: https://github.com/oxidecomputer/progenitor/issues/664

**Comment by louis030195** [comment]
@ahl oh okay thanks!

I tried progenitor but it failed with little details, let me know how to debug this to give more details, I can open issue

**Comment by ahl** [comment]
Please file an issue in the progenitor repo and we'll try to get you sorted out.
