### ISSUE TITLE
defaults

### ISSUE THREAD

**Issue by rrichardson** [oxidecomputer/typify#63]
I notice that the generated code for schemas with defaults provides serde attributes such as `default::default_i64<...>()` 
Is it intended that the user of code-generation produce those default functions? It's easy enough to do. I was just wondering if you had a library in mind. 
```

**Comment by rrichardson** [comment]
I just notice that it's also impossible to actually provide an implementation, since the structs are created inside of `mod types`  

So if I wanted to supply outside implementations of defaults, the generated attributes would need to reference  

`super::defaults`  or something.. 

Also,  Why the need for 2 type parameters?  

I've found that this seems to work: 

```rust
  mod defaults {
     pub(crate) fn default_bool<const Val: bool>() -> bool {
          Val
      }
     pub(crate) fn default_i64<const Val: i64>() -> i64 {
          Val
      }
     pub(crate) fn default_u64<const Val: u64>() -> u64 {
          Val
      }
  }
```

**Comment by rrichardson** [comment]
Also, I notice that for schemas with `type: integer`  and `default: 12`  and no `format` set, that it sets the wrong type of default value. 
The default integer is i64,  but the default is set to `default_u64<u64, 12>`  
The problem was simply that `default_fn` tests the Value for `as_u64` before it tests for `as_i64`.  So it was setting it to u64.  I reversed those.  It might need a more precise check than that.  
OpenAPI has an awful lot of edge cases to check.

**Comment by ahl** [comment]
That's **supposed** to be included from here:
https://github.com/oxidecomputer/typify/blob/f8f13fad74daa02a7485e01a0d73e611a60f887b/typify-impl/src/defaults.rs#L24

Can you include your test case?

**Comment by rrichardson** [comment]
I think I know the original cause of my issue,  I was originally processing the Duration into an i64, but it was getting the default value as a u64, since there is no way for the Value::as_i64 to ever be reached, so it was never generating the `defaults::default_i64` method in `mod defaults`  

As long as everything can be converted from a u64, which, I think is everything, then this just works.

**Comment by ahl** [comment]
Ok. I know there are still some issues lurking here. I appreciate the bug report and will try to get these pieces cleaned up.
